cf delete-route mybluemix.net --hostname wfd-menu-ic-ad-bellagio -f
cf delete-route mybluemix.net --hostname wfd-entree-ic-ad-bellagio -f
cf delete-route mybluemix.net --hostname wfd-appetizer-ic-ad-bellagio -f
cf delete-route mybluemix.net --hostname wfd-config-ic-ad-bellagio -f
cf delete-route mybluemix.net --hostname wfd-eureka-ic-ad-bellagio -f
cf delete-route mybluemix.net --hostname super-hystrix-dev -f
cf delete-route mybluemix.net --hostname super-wfd-ui-dev -f
cf delete-route mybluemix.net --hostname super-eureka-dev -f
cf delete-route mybluemix.net --hostname super-zuul-dev -f
cf delete-route mybluemix.net --hostname super-turbine-dev -f
cf delete-route mybluemix.net --hostname super-menu-dev -f
