apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netflix-turbine-pod
spec:
  replicas: 1
  template:
    metadata:
      name: netflix-turbine-pod
      labels:
        run: netflix-turbine-wfd
    spec:
      containers:
        - name: netflix-turbine
          image: "registry.ng.bluemix.net/supercontainers/netflix-turbine:dev"
          imagePullPolicy: IfNotPresent
          env:
          - name: spring_zipkin_baseUrl
            value: http://zipkin-service:9411 
          - name: eureka_client_enabled
            value: "false"
          - name: spring_rabbitmq_host
            value: "sl-us-south-1-portal.1.dblayer.com"
          - name: spring_rabbitmq_port
            value: "19377"
          - name: spring_rabbitmq_virtual_host
            value: "bmix-dal-yp-4ed4b738-3c50-4a84-8b84-5a624ff7b9d3"
          - name: spring_rabbitmq_username
            value: "admin"
          - name: spring_rabbitmq_password
            value: "KLFMSPHWWOAUENGQ"
          - name: spring_rabbitmq_ssl_enabled
            value: "true"
          - name: spring_rabbitmq_ssl_algorithm
            value: "TLSv1.2"
      imagePullSecrets:
        - name: supercontainers-secret
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-turbine-service
spec:
  type: ClusterIP
  selector:
    run: netflix-turbine-wfd
  ports:
   - protocol: TCP
     port: 8989
